name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    name: 'Publish to NuGet.org'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 'Restore packages'
      run: dotnet restore

    - name: 'Build project'
      run: dotnet build --no-restore --configuration Release

    - name: 'Get Version'
      uses: Im-Fran/version-from-tag-action@v1.0.3
      with:
        remove-first-character: 'v'

    - name: 'Pack project'
      run: dotnet pack --no-restore --no-build --configuration Release -p:PackageVersion=${{ env.VERSION }}

    - name: 'Push package'
      run: dotnet nuget push **.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
